### ISSUE TITLE
Change naming from pay/mint to "Buy"

### ISSUE THREAD

**Issue by apbendi** [showtime-xyz/creator-tokens#6]
The `payAndMint` methods should be updated to simply `buy`. The `Minted` event should be renamed to `Bought`. Variables in all tests should be updated to match. Note: `_mintAndIncrement` should remain named as such since it describes the actual minting operation happening to the token, not the higher level concept of buying.

**Comment by garyghayrat** [comment]
Changed them in the following commit: https://github.com/showtime-xyz/creator-tokens/pull/5/commits/c9ce99a68dc6dce294c80d31c7d1df8b59b9c7b9

**Comment by apbendi** [comment]
done with https://github.com/showtime-xyz/creator-tokens/pull/5
